name: Post-release version bump

# how to trigger: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Install jq
        run: sudo apt-get update; sudo apt-get install --no-install-recommends jq

      - name: Setup post-release version bump
        run: |
          # https://github.com/actions/checkout/issues/13
          # https://github.community/t/github-actions-bot-email-address/17204/6
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          # Read the current version from Cargo.toml
          current_version=$(cargo metadata --format-version 1 --no-deps | \
            jq --raw-output '.packages | .[] | select(.name == "bevy").version')
          # Sanity check: current version should be 0.X.Y
          echo "${current_version}" | grep '^0\.[0-9]\+\.[0-9]\+$'
          minor_version=$(echo "${current_version}" | sed 's/^0\.\([0-9]\+\).*/\1/')
          next_version=0.$((next_minor_version + 1)).0-dev
          # release: remove the dev suffix, like going from 0.X.0-dev to 0.X.0
          # --workspace: updating all crates in the workspace
          # --no-publish: do not publish to crates.io
          # --execute: not a dry run
          # --no-tag: do not push tag for each new version
          # --no-push: do not push the update commits
          # --exclude: ignore those packages
          cargo release "${next_version}" \
            --workspace \
            --no-publish \
            --execute \
            --no-tag \
            --no-confirm \
            --no-push \
            --exclude ci \
            --exclude errors \
            --exclude bevy-ios-example \
            --exclude spancmp \
            --exclude build-wasm-example

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          base: "main"
          title: "Bump Version after Release"
          body: |
            Bump version after release
            This PR has been auto-generated
